services:
  sb-ecom:
    build:
      context: .
      dockerfile: Dockerfile
    image: sb-ecom
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_URL=jdbc:postgresql://host.docker.internal:5432/ecommerce
      - LOGGING_FILE_PATH=/app/logs
    volumes:
      - ${HOST_IMAGES_DIR:-./images}:/app/images
      - ${HOST_LOGS_DIR:-./logs}:/app/logs
